[tool.poetry]
name = "study-ci-cd"
version = "0.1.0"
description = ""
authors = ["TomohiroFukui"]
readme = "README.md"
packages = [{ include = "my_lib" }]

[tool.poetry.dependencies]
python = "^3.12"


[tool.poetry.group.dev.dependencies]
pytest = "^9.0.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
