name: Python CI

on:
  [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - name: Install poetry
      run: pipx install poetry
    - name: Set up Python 3.12
      uses: actions/setup-python@v6
      with:
        python-version: 3.12
        cache: 'poetry'
    - name: Install dependencies
      run: poetry install
    - name: test with pytest
      run: poetry run pytest
    - name: Lint code with Ruff
      run: poetry run ruff check . --output-format=github --target-version py312